# Generated by Django 4.2.16 on 2024-11-10 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created', models.DateField(auto_now_add=True)),
                ('timeResponse', models.DateField(blank=True, null=True)),
                ('userCreated', models.CharField(max_length=100)),
                ('status', models.CharField(default='Open', max_length=100)),
                ('typePQRS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUser.typespqrs')),
            ],
        ),
    ]
