# Generated by Django 4.2.16 on 2024-11-28 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20)),
                ('areas', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(max_length=200)),
                ('asociado', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('timeResponse', models.DateTimeField(blank=True, null=True)),
                ('userCreated', models.CharField(max_length=100)),
                ('status', models.CharField(default='Open', max_length=100)),
                ('close_by', models.CharField(blank=True, max_length=100, null=True)),
                ('closed', models.DateTimeField(blank=True, null=True)),
                ('dateResponse', models.DateTimeField(blank=True, null=True)),
                ('tokenControl', models.CharField(blank=True, max_length=100, null=True)),
                ('typePQRS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUser.typespqrs')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ResponsePQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=1000)),
                ('response_by', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/responses')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pqrs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.pqrs')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pqrs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.pqrs')),
            ],
        ),
        migrations.CreateModel(
            name='Commets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.CharField(max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('created_by', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pqrs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.pqrs')),
            ],
        ),
    ]
