# Generated by Django 4.2.1 on 2025-06-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='num',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
