# Generated by Django 4.2.16 on 2024-11-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='timeResponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
