# Generated by Django 4.2.16 on 2024-11-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_pqrs_created_alter_pqrs_timeresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqrs',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='pqrs',
            name='asociado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
