# Generated by Django 4.2.16 on 2024-11-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_file_add_commets_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsePQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=1000)),
                ('response_by', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/responses')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pqrs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.pqrs')),
            ],
        ),
    ]
