# Generated by Django 4.2.16 on 2024-11-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_pqrs_options_pqrs_asociado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.CharField(max_length=1000)),
                ('created_by', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pqrs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.pqrs')),
            ],
        ),
    ]
