# Generated by Django 4.2.16 on 2024-11-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pqrs_dateresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrs',
            name='tokenControl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
