# Generated by Django 4.2.16 on 2024-11-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_commets_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='commets',
            name='file_add',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='commets',
            name='image_add',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='close_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
